name: Daily Loaders Test
on:
  schedule:
    - cron: '00 23 * * *' # Runs at midnight UTC every day
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Initialize Node.js
        uses: ./.github/actions/init-node
      - name: Loaders Test
        run: node --run test:audit
