name: Close Preview
on:
  pull_request:
    types:
      - closed
    paths-ignore:
      - '**/*.md'
      - 'proxy/**'
      - 'server/**'
      - 'scripts/**'
      - '.vscode/**'
      - '.husky/**'
      - '.github/**'
      - 'core/test/**'
      - 'loader-tests/**'
      - '.devcontainer/**'
      - 'extension/**'
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        run: echo "${{ github.event.pull_request.number }}" > ./preview-id
      - name: Save data for another workflow
        uses: actions/upload-artifact@v4
        with:
          name: preview-id
          retention-days: 1
          path: |
            ./preview-id
