name: Start Preview Deployment
on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'proxy/**'
      - 'server/**'
      - 'scripts/**'
      - '.vscode/**'
      - '.husky/**'
      - '.github/**'
      - 'core/test/**'
      - 'loader-tests/**'
      - '.devcontainer/**'
      - 'extension/**'
permissions:
  contents: read
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.7
      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Build assets
        run: cd web && node --run build
        env:
          STAGING: 1
      - name: Build server
        run: cd server && node --run build
      - name: Save PR number
        run: echo "${{ github.event.pull_request.number }}" > ./preview-id
      - name: Create archive to keep symlinks
        run: tar -cf server.tar server/dist/
      - name: Save server for deploy
        uses: actions/upload-artifact@v4.4.0
        with:
          name: preview-server
          retention-days: 1
          include-hidden-files: true
          path: |
            server/web/
            server/Dockerfile
            server/.dockerignore
            preview-id
            server.tar
