name: Test
env:
  FORCE_COLOR: 2
on:
  push:
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./.yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable --skip-builds
      - name: Run tests
        run: yarn test
