name: Test
env:
  FORCE_COLOR: 2
on:
  push:
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Install dependencies
        uses: yarn install --immutable
      - name: Run tests
        run: yarn test
